apiVersion: apps/v1
kind: Deployment
metadata:
  name: kz-pharmacy-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /kz-openapi
            - name: BASE_URL
              value: /kz-openapi-ui