apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: kabac-zalabai-install  # v spoločnom klastri je nasadených viacero takýchto objektov
 namespace: wac-hospital
spec:
 wait: true
 interval: 120s
 path: clusters/wac-aks/install
 prune: true
 sourceRef:
     kind: GitRepository
     name: kabac-zalabai-gitops-repo