apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: kabadrian/pharmacy-webapi
  newName: kabadrian/pharmacy-webapi # {"$imagepolicy":  "wac-hospital:pharmacy-webapi:name"}
  newTag: main.20240424.1455 # {"$imagepolicy": "wac-hospital:pharmacy-webapi:tag"}
- name: kabadrian/pharmacy-ufe
  newName: kabadrian/pharmacy-ufe # {"$imagepolicy":  "wac-hospital:pharmacy-ufe:name"}
  newTag: main.20240319.1031 # {"$imagepolicy": "wac-hospital:pharmacy-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
